version: "2"
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
    volumes:
      - "redis_data:/data"
      - ".:/app"
  main:
    image: my/rails:latest
    volumes:
      - ".:/app"
      - "ruby_bundle:/usr/local/bundle"
      - "rails_log:/app/log"
      - "rails_tmp:/app/tmp"
      - "/Users/alshin/.ssh/id_rsa:/root/.ssh/id_rsa"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres@db
    depends_on:
      - db
      - redis
    command: bundle exec rails s

volumes:
  postgres_data:
  redis_data:
  ruby_bundle:
  rails_tmp:
  rails_log:
